config/routes.rb
Rails.application.routes.draw do
  resources :cibos
  root :to => 'data#input'
  get 'data/input'
  get 'data/search'

end

app/models/cibo.rb
class Cibo < ActiveRecord::Base
end

app/models/top_food.rb
class TopFood < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def input
  end

  def search
    query="%" + params[:search] + "%"
    @query_full = Cibo.where('name=?', params[:search]).first
    puts @query_full.inspect
    @otomatis = Cibo.where('name LIKE ?', query).limit(15).pluck(:name)
    @results = Instagram.tag_recent_media(name = 'chicken', {:count => 5})
    puts @otomatis.inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_food_data.html.erb
<p>Name : <%= raw @query_full.try(:name) %></p>
<% @results.each do |ig| %>
<li>
<%= image_tag ig.images.thumbnail.url  %>
</li>
<% end %>

app/views/data/_idfood.html.erb
<h2>Suggestion Indonesian top dishes</h2>
<ul id="foodList">

    	<% TopFood.where(:country => 'ind').order('RANDOM()').find_each do |food| %>
    	<li><%= food.name  %></li>
    	<% puts food.inspect %> 
	<% end %>

</ul>
<div id="loadMore">More sugesstions</div>
<div id="showLess">Show less</div>

app/views/data/_intfood.html.erb
	<h2>Suggestion International top dishes</h2>
	<ul id="foodList">
		
  
	</ul>
	<div id="loadMore">More sugesstions</div>
	<div id="showLess">Show less</div>

app/views/data/input.html.erb
<div class="container">
	<div class="row row-centered">
		<div class="col-xs-6 col-centered">
<h1>What foods that what you want?</h1>
<div class="checkbox">
<%= check_box_tag 'id-food', 'indonesian-food', class: 'checkbox'  %>
<%= label_tag :checkbox, 'Indonesian food' %>
</div>
<div class="checkbox">
<%= check_box_tag 'in-food', 'international-food', class: 'checkbox'  %>
<%= label_tag :checkbox, 'International food' %>
</div>
	<div id="open-id">
		<%= render "idfood"  %>
	</div>
	<div id="open-in">
		<%= render "intfood"  %>
	</div>
	<div id="form_search">
		<%= form_tag data_search_path, method:'get', remote: true do   %>
		<%= text_field_tag :search, '', size:20, :autocomplete => :off, :class => "searchbox"  %>
		<%= submit_tag 'search', :id => 'search_key', :style => "display: none;" %>
		<% end %>
	</div>

<div id="food"></div>
</div>
</div>
</div>

app/views/data/search.html.erb
<h1>Data#search</h1>
<p>Find me in app/views/data/search.html.erb</p>

app/views/data/search.js.erb
$(function() {
	var availableTags = <%= raw @otomatis  %>;
	$( "#search" ).autocomplete({
		source: availableTags
	});
});
$('#food').html("<%= j render 'food_data'  %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
				<%= yield %>
</body>
</html>